import { createElement } from 'lwc';
import Lwc_eventparent_volume_080923 from 'c/lwc_eventparent_volume_080923';

describe('c-lwc-eventparent-volume-080923', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-eventparent-volume-080923', {
            is: Lwc_eventparent_volume_080923
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});