import { createElement } from 'lwc';
import Lwc_variable_input_060723 from 'c/lwc_variable_input_060723';

describe('c-lwc-variable-input-060723', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-variable-input-060723', {
            is: Lwc_variable_input_060723
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});